database:
  host: "192.168.56.3"
  port: 5432
  username: "admin"
  password: "admin"
  name: "students"
  ssl_mode: "disable"

kafka:
  host: "192.168.56.3"
  port: 9092
  room_events_topic: "rooms.events"
  player_commands_topic: "players.commands"
  chat_commands_topic: "chat.commands"

redis:
  host: "192.168.56.3"
  port: 6379
  password: ""
  db: 0
  ttl_seconds: 3600